name: epochconv
version: '1.4'
license: ISC
copyright: 2014-2021 Dino Morelli
author: Dino Morelli
maintainer: dino@ui3.info
synopsis: Convert between epoch and various date formats
description: Show a given date (or the current date) in a variety of formats. This was partly an exercise in grokking the Haskell date/time APIs.
category: Application, Console

extra-source-files:
- .gitignore
- hsinstall/share/icons/hicolor/scalable/apps/epochconv.svg
- hsinstall/share/applications/epochconv.desktop
- package.yaml
- README.md
- stack.yaml
- stack.yaml.lock

ghc-options:
- -fwarn-tabs
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

executables:
  epochconv:
    source-dirs: .
    main: epochconv.hs
    dependencies:
    - base >= 4.7 && < 5.0
    - time
